### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by hejialianghe** [waysact/webpack-subresource-integrity#215] opened 2023-03-22 02:45 UTC
The following error prompt occurred during the download operation：

TypeError: Class extends value undefined is not a constructor or null

**Comment by jscheid** [comment] 2023-03-22 15:55
Duplicate of #174, you're using version 5 of this plugin with version 4 (or older) of Webpack. You need to upgrade Webpack or downgrade this plugin.

**Closed by jscheid** 2023-03-22 15:55 UTC
