### ISSUE TITLE
SRI warning for ng build 

### ISSUE THREAD

**Issue by Grace-Dmello** [waysact/webpack-subresource-integrity#121] opened 2019-10-07 22:42 UTC
WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.c665f7f0f030771d6d1a.js.

**Comment by jscheid** [comment] 2019-10-08 20:44
Thanks, dlosing this as a duplicate of #104.

**Closed by jscheid** 2019-10-08 20:44 UTC
