### ISSUE TITLE
multi page add all srihash?can include hash  split?

### ISSUE THREAD

**Issue by WilsonLiu95** [waysact/webpack-subresource-integrity#100] opened 2019-01-15 13:40 UTC
I use webpack to build multi web.I want to inline the runtime js file.So I split runtime multi.but the sri include all. can config it?

**Comment by jscheid** [comment] 2019-01-15 20:48
Sorry, I don't understand what the problem is. Could you make an example repository?

**Comment by jscheid** [comment] 2019-01-21 05:53
I'm going to close this because I don't know what to do here, but feel free to reopen with a link to a repository that demonstrates the problem and I'm happy to take another look.

**Closed by jscheid** 2019-01-21 05:53 UTC
