### ISSUE TITLE
Issue with integrity build

### ISSUE THREAD

**Issue by bnupy** [waysact/webpack-subresource-integrity#140] opened 2020-12-08 15:32 UTC
WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.95460c9f91f9338b7eb9.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new

**Comment by jscheid** [comment] 2021-01-13 22:03
Thanks, closing as a duplicate of #141

**Closed by jscheid** 2021-01-13 22:03 UTC
