### ISSUE TITLE
Integrity fail with Critters

### ISSUE THREAD

**Issue by blephy** [waysact/webpack-subresource-integrity#105] opened 2019-03-13 21:18 UTC
Hi,

I'm using [Critters](https://github.com/GoogleChromeLabs/critters) to deal with critical css.
Critters is running after the webpack build. Can we deal with this and recalculate the integrity value on .css links processed with Critters ?

I'm getting a browser integrity value failed.

**Comment by jscheid** [comment] 2019-03-22 02:58
I've added a test case and it works fine.

You need to provide some more context, [see here](https://github.com/waysact/webpack-subresource-integrity/blob/master/CONTRIBUTING.md).

**Comment by jscheid** [comment] 2019-04-02 08:22
I'm going to close this because without being able to reproduce it there's not much I can do. Please feel free to reopen with some more context, ideally a small repository that demonstrates the issue.

**Closed by jscheid** 2019-04-02 08:22 UTC
