### ISSUE TITLE
WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined"

### ISSUE THREAD

**Issue by vasyliv** [waysact/webpack-subresource-integrity#108] opened 2019-05-07 10:50 UTC
Here is the warning:
```
WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.a6bfd8cd0af627017117.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new
```

here is code
```
function googleTranslateElementInit(){"undefined"!=typeof google&&new google.translate.TranslateElement({pageLanguage:"en",layout:google.translate.TranslateElement.InlineLayout.SIMPLE},"google_translate_element")}!function(e){var t={};function n(a){if(t[a])return t[a].exports;var o=t[a]={i:a,l:!1,exports:{}};return e[a].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,a){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(n.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(a,o,(function(t){return e[t]}).bind(null,o));return a},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}([function(e,t){"undefined"!=typeof window&&(window.VERSION="2019-04-15T05:35:55.417Z")}]),function(e,t,n,a,o,r,l){e.GoogleAnalyticsObject="ga",e.ga=e.ga||function(){(e.ga.q=e.ga.q||[]).push(arguments)},e.ga.l=1*new Date,r=t.createElement(n),l=t.getElementsByTagName(n)[0],r.async=1,r.src="https://www.google-analytics.com/analytics.js",l.parentNode.insertBefore(r,l)}(window,document,"script"),function(e,t,n){e&&t&&function(e,t){var n=new Date;function a(e){var n=t.getElementsByTagName("head")[0];n||(n=t.body.parentNode.appendChild(t.createElement("head"))),n.appendChild(e)}e.addEventListener&&void 0===t.readyState&&e.addEventListener("DOMContentLoaded",function(){t.readyState="complete"},!1),function(t){t=t.split(".");for(var n=e,a=0;a<t.length;++a)if(!(n=n[t[a]]))return!1;return!0}("google.translate.Element")||function(){var o=function(t){t=t.split(".");for(var n=e,a=0;a<t.length;++a)n=n.hasOwnProperty?n.hasOwnProperty(t[a])?n[t[a]]:n[t[a]]={}:n[t[a]]||(n[t[a]]={});return n}("google.translate._const");o._cest=n,n=void 0,o._cl="en",o._cuc="googleTranslateElementInit",o._cac="",o._cam="",o._ctkk="427170.2388829369";var r,l="translate.googleapis.com",i="https://",s=i+l;o._pah=l,o._pas=i,o._pbi=s+"/translate_static/img/te_bk.gif",o._pci=s+"/translate_static/img/te_ctrl3.gif",o._pli=s+"/translate_static/img/loading.gif",o._plla=l+"/translate_a/l",o._pmi=s+"/translate_static/img/mini_google.png",o._ps=s+"/translate_static/css/translateelement.css",o._puh="translate.google.com",function(e){var n=t.createElement("link");n.type="text/css",n.rel="stylesheet",n.charset="UTF-8",n.href=e,a(n)}(o._ps),(r=t.createElement("script")).type="text/javascript",r.charset="UTF-8",r.src="https://translate.googleapis.com/translate_static/js/element/main.js",a(r)}()}(e,t)}("undefined"!=typeof window?window:null,"undefined"!=typeof document?document:null);
```

**Comment by jscheid** [comment] 2019-05-12 10:37
Thanks! Closing this as a duplicate of #104.

**Closed by jscheid** 2019-05-12 10:37 UTC
