### ISSUE TITLE
Error loading Workers as Asset Modules

### ISSUE THREAD

**Issue by AprilArcus** [waysact/webpack-subresource-integrity#165] opened 2021-08-12 03:51 UTC
Hi folks! I am having problems [loading workers as asset modules](https://webpack.js.org/guides/web-workers/) in conjunction with subresource integrity plugin and the use of [`contenthash`](https://webpack.js.org/configuration/output/#template-strings) in [chunk file names](https://webpack.js.org/configuration/output/#outputchunkfilename). Any two of the following will work:
  * SRI Plugin
  * `new Worker(new URL(..., import.meta.url))`
  * output.chunkFilename: '[contenthash]'

Minmal reproduction: https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro
See also: https://github.com/webpack/webpack/issues/13801

**Comment by AprilArcus** [comment] 2021-08-12 05:50
Minimal repro: https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro

**Comment by roninjin10** [comment] 2021-08-12 15:37
I was able to make an even more minimal repro where I stripped out everything except the hook that was causing this bug to happen AprilArcus/webpack-sri-workers-contenthash-repro#1 

It appears to me to be a webpack bug triggered by service workers (or potentially more generally async chunks but I didn't test this) and the plugin calling `mainTemplate.hooks.localVars.tap`.  In my repro I stripped out every piece of code except that call and reproduced the bug.

**Comment by jscheid** [comment] 2021-08-12 18:45
Thanks for the repro. On the Webpack issue you said:

> by simply tapping into `mainTemplate.hooks.localVars.tap` and doing nothing else it triggered this behavior

This sounds like an issue in Webpack so I'm closing this. Feel free to reopen if it turns out there's something we can do at our end to help.

**Closed by jscheid** 2021-08-12 18:45 UTC
