### ISSUE TITLE
Plugin doesn't work with webpack watch

### ISSUE THREAD

**Issue by juchiast** [waysact/webpack-subresource-integrity#107] opened 2019-04-26 03:07 UTC
When using this plugin with `webpack watch`, the first build succeed but after that, it produces `integrity="null"`.

Btw, I see you mentioning problems with hot reloading in README, does this apply to `webpack watch` too?

**Comment by jscheid** [comment] 2019-04-26 03:25
Hi, thanks for the bug report.

Could you provide a test case? A small sample repository would be enough.

> Btw, I see you mentioning problems with hot reloading in README, does this apply to webpack watch too?

No, hot reloading refers to [HMR](https://webpack.js.org/concepts/hot-module-replacement/) and that's related to watch mode but not the same. Watch mode should work, we have a [test case](https://github.com/waysact/webpack-subresource-integrity/blob/daeddb44f0b5019809adab1dee4b1b53ed82d179/test/test-misc.js#L94]) for it.

Out of curiosity, why do you need to use integrity with watch mode? Usually watch is only used in development mode, and in development mode integrity is normally not important (because you wouldn't be using a CDN or such.) See https://github.com/waysact/webpack-subresource-integrity#enabled

**Comment by jscheid** [comment] 2019-04-30 00:07
I'm afraid there's nothing I can do here without knowing how to reproduce the issue so I'm going to close this. Feel free to reopen when you can provide some more information.

**Closed by jscheid** 2019-04-30 00:07 UTC
