### ISSUE TITLE
WARNING in webpack-subresource-integrity:

### ISSUE THREAD

**Issue by Emanuel-Gill** [waysact/webpack-subresource-integrity#128] opened 2020-09-18 11:18 UTC
Cannot determine asset for chunk scripts, computed="undefined", available=scripts.b84d85e55bd4a8995fb5.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new

**Comment by jscheid** [comment] 2020-10-12 09:02
Thanks, this happens with older angular-cli versions which depend on an old version of this plugin. Upgrading to angular-cli 10 should fix it.

Closing as a duplicate of #104

**Closed by jscheid** 2020-10-12 09:02 UTC
