### ISSUE TITLE
ng build --prod ERROR in Cannot assign to a reference or variable!

### ISSUE THREAD

**Issue by jeromeDevIN** [waysact/webpack-subresource-integrity#120] opened 2019-10-05 09:31 UTC
Hello,

Here is the error message I get after a ng build --prod on Angular app. Could you help me to resolve this problem please ?

> 

ERROR in Cannot assign to a reference or variable!
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/@angular/material/prebuilt-themes/indigo-pink.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.07 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 64.2 KiB [entry] [rendered]
     [Ysuc] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/@angular/material/prebuilt-themes/indigo-pink.css 64.2 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!c:\angular\test-nebular_1_19_0\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!c:\angular\test-nebular_1_19_0\node_modules\postcss-loader\src\index.js??extracted!c:\angular\test-nebular_1_19_0\node_modules\@angular\material\prebuilt-themes\indigo-pink.css  mini-css-extract-plugin
         factory:8ms building:343ms = 351ms
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/@nebular/theme/styles/prebuilt/default.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  2.14 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 146 KiB [entry] [rendered]
     [i5tx] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/@nebular/theme/styles/prebuilt/default.css 146 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!c:\angular\test-nebular_1_19_0\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!c:\angular\test-nebular_1_19_0\node_modules\postcss-loader\src\index.js??extracted!c:\angular\test-nebular_1_19_0\node_modules\@nebular\theme\styles\prebuilt\default.css  mini-css-extract-plugin
         factory:72ms building:286ms = 358ms
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/bootstrap/dist/css/bootstrap.min.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.26 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 153 KiB [entry] [rendered]
     [aogg] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/bootstrap/dist/css/bootstrap.min.css 153 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!c:\angular\test-nebular_1_19_0\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!c:\angular\test-nebular_1_19_0\node_modules\postcss-loader\src\index.js??extracted!c:\angular\test-nebular_1_19_0\node_modules\bootstrap\dist\css\bootstrap.min.css  mini-css-extract-plugin
         factory:74ms building:423ms = 497ms
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--15-3!src/styles.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.26 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 236 bytes [entry] [rendered]
     [/c4r] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss 236 bytes {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!c:\angular\test-nebular_1_19_0\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!c:\angular\test-nebular_1_19_0\node_modules\postcss-loader\src\index.js??extracted!c:\angular\test-nebular_1_19_0\node_modules\sass-loader\lib\loader.js??ref--15-3!c:\angular\test-nebular_1_19_0\src\styles.scss  mini-css-extract-plugin
         factory:258ms building:45ms = 303ms

WARNING in Conflict: Multiple assets emit different content to the same filename 3rdpartylicenses.txt

WARNING in Conflict: Multiple assets emit different content to the same filename 3rdpartylicenses.txt

WARNING in Terser Plugin: Dropping unused variable sriHashes_1 [runtime-es2015.c13f31dd9f49759182a3.js:64,14]

WARNING in Terser Plugin: Dropping unused variable sriHashes_2 [runtime-es2015.c13f31dd9f49759182a3.js:64,14]

WARNING in Terser Plugin: Dropping unused variable sriHashes_3 [runtime-es2015.c13f31dd9f49759182a3.js:64,14]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.4513c2c88dc8c3fd5569.js:2,66549]

WARNING in Terser Plugin: Dropping unreachable code [scripts.4513c2c88dc8c3fd5569.js:2,83630]

WARNING in Terser Plugin: Declarations in unreachable code! [scripts.4513c2c88dc8c3fd5569.js:2,83630]

WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.4513c2c88dc8c3fd5569.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new

ERROR in Cannot assign to a reference or variable!

**Comment by jscheid** [comment] 2019-10-05 19:21
The error is `Cannot assign to a reference or variable!`. I can see why you think that this plugin is causing it, but the output is misleading. The error just happens to be printed next to a warning emitted by this plugin. A quick search brings up [this SO question and solution](https://stackoverflow.com/questions/42437822/angular-2-form-validation-error-unhandled-promise-rejection-cannot-assign-to-a).

As for the warning, it's caused by `angular-cli` using an old version of this plugin. If you want to get rid of it, you can try upgrading to `angular-cli@9.0.0-next`, or have a look [here](https://github.com/waysact/webpack-subresource-integrity/issues/104#issuecomment-460535274).

Hope this helps, good luck!

**Closed by jscheid** 2019-10-05 19:21 UTC
